# generated by datamodel-codegen:
#   filename:  swagger.json
#   timestamp: 2022-07-18T09:33:07+00:00

from __future__ import annotations

from pydantic import BaseModel


class RawExtension(BaseModel):
    pass
